default:
  image: node:20-alpine
  tags:
    - cluster

cache:
  key: "$CI_PIPELINE_IID"
  paths:
    - node_modules/

stages:
  - install
  - release
  - publish

install:
  stage: install
  script:
    - npm --userconfig=$NPMRC ci
  tags:
    - cluster

publish-snapshot:
  stage: publish
  only:
    - develop
  script:
    - npm --userconfig=$NPMRC --registry=$NPM_REGISTRY_SNAPSHOTS publish

publish-release:
  stage: publish
  only:
    - tags
  script:
    - npm --userconfig=$NPMRC --registry=$NPM_REGISTRY_RELEASES publish
  tags:
    - cluster